### ISSUE TITLE
Support log retention

### ISSUE THREAD

**Issue by czchen** [pm2-hive/pm2-logrotate#1]
pm2-logrotate does not have any configure to remove old log file after retention period. To prevent disk full, we need to use another log logrotate tool like logrotate to do retention. It would be great if it can be done in pm2-logrotate.

**Comment by daraghking** [comment]
I had a go at implementing retention - [link](https://github.com/daraghking/pm2-logrotate). I made a few other minor changes. I would love your feedback. Maybe we can get it merged in after it is refined.

**Comment by czchen** [comment]
@daraghking I think the default value of `delete_after` shall be `7` or `30` to prevent disk full in long running system, and to keep enough log for troubleshooting. If user want to keep all log, they can set `delete_after

**Comment by daraghking** [comment]
I don't like the idea of deleting someones logs by default. This way they have to opt-in.

**Comment by czchen** [comment]
It is okay for me if the default is not to delete any log.

**Comment by jshkurti** [comment]
https://github.com/pm2-hive/pm2-logrotate/pull/2
