### ISSUE TITLE
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes

### ISSUE THREAD

**Issue by tzaitsev** [pm2-hive/pm2-logrotate#10]
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
    at new Buffer (buffer.js:72:11)
    at Object.fs.readFileSync (fs.js:374:16)
    at proceed (/home/ubuntu/.pm2/node_modules/pm2-logrotate/app.js:70:19)
    at proceed_file (/home/ubuntu/.pm2/node_modules/pm2-logrotate/app.js:92:5)
    at proceed_app (/home/ubuntu/.pm2/node_modules/pm2-logrotate/app.js:101:3)
    at /home/ubuntu/.pm2/node_modules/pm2-logrotate/app.js:133:37
    at Array.forEach (native)
    at /home/ubuntu/.pm2/node_modules/pm2-logrotate/app.js:133:14
    at /home/ubuntu/.pm2/node_modules/pm2-logrotate/node_modules/pm2/lib/CLI.js:1387:17
    at /home/ubuntu/.pm2/node_modules/pm2-logrotate/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10

**Comment by alavit-d** [comment]
Hi,

This happens when trying to read a file heavier than 1GB. However log files over 5M should be split up automatically with the default config. What are your current conf values for this module? Is your application very verbose?

**Comment by xuyongtao** [comment]
I have the same problem, my conf values is 
pm2 set pm2-logrotate:max_size 524288000 
pm2 set pm2-logrotate:interval_unit 'DD' 
pm2 set pm2-logrotate:interval 1 
pm2 set pm2-logrotate:retain 180

**Comment by kha0S** [comment]
I found the same problem. Error trying to rotate at 2GB, 1GB. Testing now with 512MB.

**Comment by alavit-d** [comment]
Hi, 

I used streams to get rid of the 1G issue, it should also use less memory ( cf https://github.com/pm2-hive/pm2-logrotate/issues/8) . Could I have your feedback on this before posting to npm? (install the master branch with `pm2 install pm2-hive/pm2-logrotate`).

Thanks!

**Comment by kha0S** [comment]
Thanks!
Testing right now.

**Comment by alavit-d** [comment]
New version live on npm - 1.3.1
