### ISSUE TITLE
Cannot remove empty config

### ISSUE THREAD

**Issue by asendia** [pm2-hive/pm2-logrotate#11]
Hello there,
I accidentally write `pm2 set pm2-logrotate: interval 1` (notice the space between : and interval)
Then I remove the empty key by typing `pm2 set pm2-logrotate: ''` but there will be empty row left:

key | value
----- | ------
interval_unit | DD
(empty) | (empty)
retain | 7

How can I remove the empty key-value from the config?

**Comment by alavit-d** [comment]
Hi,
Thanks for reporting, does this affect the application in any way?
For removing it you can edit `module_conf.json` in your pm2 folder (default `~/.pm2/module_conf.json`) which contains every module configuration.
Edit the JSON and remove the unwanted entry from the pm2-logrotate object.

**Comment by asendia** [comment]
@alavit-d thanks for the fast answer. It does not affect the application.
