### ISSUE TITLE
logrotate rotate the log multiple times if   merge_logs is true

### ISSUE THREAD

**Issue by zhongfox** [pm2-hive/pm2-logrotate#14]
if we config the pm2 app like this: 

...
merge_logs": true,
"instances": "3"
...

so the 3 instances will use one log file, but now pm2-logrotate will rotate the file 3 times, each information will appear 3 times in the new logrotate file

**Comment by tangxinfa** [comment]
The same problem.

**Comment by Unitech** [comment]
The code for the pm2-logrotate module is straightforward: https://github.com/pm2-hive/pm2-logrotate/blob/master/app.js

Could you please have a look,

**Comment by tangxinfa** [comment]
@Unitech 
I created a pull request to fix this issue: https://github.com/pm2-hive/pm2-logrotate/pull/23

@zhongfox 
I already tested my pull request it works, please give a try:

    pm2 install tangxinfa/pm2-logrotate

**Comment by vmarchaud** [comment]
Fixed in latest update (v2.0.0).
