### ISSUE TITLE
Fast growing log files may be overwritten

### ISSUE THREAD

**Issue by bragma** [pm2-hive/pm2-logrotate#18]
The worker job is executed every 50 seconds and the rotated file name has a format of year-month-day-hour-minutes. This may lead to overwrite files is the worker starts in the first 10 seconds of the minute and the log file grows fast enough to exceed 'max_size'. As an example, if the worker is started at 10:00:05 and truncates a file, the worker will execute again at 10:00:55. If the file needs to be rotated again, it will get the same name and be overwritten.

**Comment by vmarchaud** [comment]
You can configure the date_format (use milliseconds for example) in the new version to avoid this problem.
