### ISSUE TITLE
Log File Size exceeding Max Size config value

### ISSUE THREAD

**Issue by ColinMc** [pm2-hive/pm2-logrotate#19]
I'm currently running into an issue where the log files are exceeding the max size limit for a log file. Configuration is the following:
```json
{ "max_size": "50M", "retain": "20" }
```

Here is an example of file when I do "ls -lh":
```text
564M Dec  7 07:01 App__2015-12-06-07-01.log
```

Twenty files are being created with various sizes from 259 MB up to 614 MB. The current log is the only one that seems to be less than what I specified; currently it's 43 MB.

My understanding based off the config I set is I should have 21 files and all of them 50 MB each.

Off topic but wondering why file rotation names aren't .log.1 and so forth. I come from a Java background and usually you can configure it to be time-based or size based which would have the .log.1 extension.

**Comment by davestevens** [comment]
I assume that its to do with when the logs are checked:
https://github.com/pm2-hive/pm2-logrotate/blob/master/app.js#L105-L107
It won't split the files to be exactly 50M, its just if they're over the limit at the time of checking then they will be rotated.

**Comment by vmarchaud** [comment]
Exactly, it trigger the split if the size is superior than the configuration ONLY when the worker check the logs, you can configure when the worker check with new version if you want thought.
