### ISSUE TITLE
Please warnning user if free disk space is low

### ISSUE THREAD

**Issue by tangxinfa** [pm2-hive/pm2-logrotate#21]
My server is low free disk space because of pm2 log files, so i install pm2-logrotate, it start running, split log files, but it occupy more space quickly. Finally i manually remove all log files and do "pm2 kill" to makesure all log files closed to really free disk space. This is my story, hopes there is a warnning before i do it:(

**Comment by vmarchaud** [comment]
If you are using Keymetrics, you can setup a threshold for the size used for logs with the new version of pm2-logrotate, or use pm2-server-monit and setup a threshold for disk usage.
You can use the new option `compress` to zip log file, that should take less space.
