### ISSUE TITLE
pm2-logrotate is not working 

### ISSUE THREAD

**Issue by rasekar2000** [pm2-hive/pm2-logrotate#22]
RajRajen:lb4b-api rajrajen$ pm2 set pm2-logrotate:max_size 100K
== pm2-logrotate ==
┌──────────┬───────┐
│ key      │ value │
├──────────┼───────┤
│ max_size │ 100K  │
└──────────┴───────┘
RajRajen:lb4b-api rajrajen$ pm2 save
[PM2] Dumping processes
RajRajen:lb4b-api rajrajen$ ls -lhart /Volumes/DataPartition/MyData2/pm2/logs
total 2448
-rw-r--r--   1 rajrajen  staff   637K Dec 26 23:35 lb4b-api-out-old.log
drwxr-xr-x  12 rajrajen  staff   408B Dec 27 09:54 ..
drwxr-xr-x   5 rajrajen  staff   170B Dec 27 09:54 .
-rw-r--r--   1 rajrajen  staff   3.5K Dec 27 09:55 lb4b-api-error-0.log
-rw-r--r--   1 rajrajen  staff   576K Dec 27 10:07 lb4b-api-out-0.log
RajRajen:lb4b-api rajrajen$ 

Eventhough , I setup the pm2-logrotate at 100K , the process continues to dump log files in only one out log file. Is there anything else, I need to validate this one? Please let me know. Thanks

**Comment by davestevens** [comment]
I made a mistake in not activating pm2. Note that its `pm2 install` and not `npm install`. When installed you should see that the module is active when using `pm2 ls`.

**Comment by rasekar2000** [comment]
I have seen pm2 log rotate in recent times. Will come back to you ..

**Comment by tangxinfa** [comment]
According to the pm2-logrotate 1.3.1 implemention detail:

max_size is not means the log files rotated will has this size, it just one condition to trigger the "split" logic, second condition to trigger the "split" logic is current date time(specified by interval and interval_unit config options) changed.

"split" is simply move the current log file to a new file named with <project name>-out__YYYY-MM-DD-HH-mm.log, so if log output too frequently(log output exceed max_size in 1 minutes), log file overwrite occured(conflict file naming), lose your old log.

**Comment by vmarchaud** [comment]
Fixed in latest update (v2.0.0).
