### ISSUE TITLE
logrotate not work when one month is over

### ISSUE THREAD

**Issue by ykan** [pm2-hive/pm2-logrotate#26]
I use pm2-logrotate just fine. But when a month is over, pm2-logrotate suddenly not work... 

I look for the pm2-logrotate file, but I can't find any reason...

**Comment by yatping** [comment]
I got the same problem

**Comment by Emilio-Gonzalez** [comment]
Me too

**Comment by Unitech** [comment]
I m currently focused on releasing PM2 version 2, can anyone check the issue in the code:
https://github.com/pm2-hive/pm2-logrotate/blob/master/app.js

It's quite trivial!

**Comment by vmarchaud** [comment]
Fixed in latest update (v2.0.0).

**Comment by hanhaotian87** [comment]
now , my version 2.6.0 repeat
