### ISSUE TITLE
Rotating non-root user logs?

### ISSUE THREAD

**Issue by richRemer** [pm2-hive/pm2-logrotate#27]
When I attempt to install pm2-logrotate with a non-root user, I receive the following error:

$ pm2 install pm2-logrotate
[PM2][Module] Installing module pm2-logrotate
[PM2][Module] Processing...
[PM2][Module][ERROR] Unknown module

If I do the same as the root user, the module installs fine:

$ sudo pm2 install pm2-logrotate
[PM2][Module] Installing module pm2-logrotate
[PM2][Module] Processing...
....
[PM2][Module] Module downloaded
[PM2][WARN] Applications pm2-logrotate not running, starting...
[PM2] App [pm2-logrotate] launched (1 instances)
[PM2][Module] Module successfully installed and launched
[PM2][Module] : To configure module do
[PM2][Module] : $ pm2 conf <key> <value>

But when I execute pm2 status for the non-root user, I do not see the module.  Does this rotate the logs for all users?  It doesn't seem to be doing anything at all.  My log files continue to get larger.  I've set the interval to 1 minute, restarted PM2, re-created PM2 service jobs, and still nothing.

**Comment by vmarchaud** [comment]
You just need to give the right to PM2 over the logs file, the module is running with PM2's rights.

**Comment by itjustwerks** [comment]
I know this is old, but I'm running into the same issue. I installed pm2-logrotate while logged in as a non-root user, but the Module is showing with "root" in the user column and is only visible via ```pm2 list``` when I'm logged into the server as root. 

How can I get logrotate to clean up log files for PM2 instances running under non-root users?
