### ISSUE TITLE
[PM2][Module][ERROR] Unknown module

### ISSUE THREAD

**Issue by s-a** [pm2-hive/pm2-logrotate#31]
cannot install it on windows. 

```bash
pm2 -v
1.1.3
```

**Comment by s-a** [comment]
this is related to pm2 and currently fixed in pm2 repository but not published to npm.

**Comment by aryeharmon** [comment]
having the same issue

**Comment by Unitech** [comment]
PM2 v2 has better Windows support:

```
$ npm install pm2@next -g
```
