### ISSUE TITLE
Is there a way to set timezone?

### ISSUE THREAD

**Issue by smilechun** [pm2-hive/pm2-logrotate#32]
Hi alls,
I would like to rotate log file per date every midnight in my local timezone and avoid changing the system timezone.

**Comment by vmarchaud** [comment]
@smilechun Hello, actually its not possible, we will push an update ASAP to do this, thanks for feedback ;)

**Comment by vmarchaud** [comment]
Hello, we are using [node-schedule](https://github.com/node-schedule/node-schedule) to setup the cron job, it doesnt seems to be possible to do this, sorry.
