### ISSUE TITLE
setting a custom pm2-logrotate path 

### ISSUE THREAD

**Issue by Qrishna** [pm2-hive/pm2-logrotate#35]
Hello,

Currently, pm2-logrotate seems to rotate its own logs under wherever PM2_HOME is set. Even though the logs produced by the application managed by pm2 can be set to go to a custom location, the pm2-logrotate's own logs(pm2-logrotate-error-0.log, pm2-logrotate-out-0.log
) just go under PM2_HOME. How can we define a custom path to make these logs go to a certain place? How can we override this default path?

Thank you so much,
KB

**Comment by vmarchaud** [comment]
Currently not possible with PM2, the module can't tell pm2 where his logs are going, so by default all module logs will go to PM2_HOME :/
I'm making an issue on the pm2 repo tho

**Comment by vmarchaud** [comment]
You'll need to git clone the repository, modify the[ package.json](https://github.com/pm2-hive/pm2-logrotate/blob/master/package.json#L25) like you may do with a process file (in your case add the `error-log` configuration)
Then you just need to run `pm2 install .` in the directory of the modified module and it should work
