### ISSUE TITLE
Delete compressed logs

### ISSUE THREAD

**Issue by UVk** [pm2-hive/pm2-logrotate#36]
Hi,

I would like to know if it is possible to delete the compressed files with post rotate script or something similar to that.
My problem is that I have small disk space and it's getting full quickly.

Thanks

**Comment by anmolgupta** [comment]
I am facing the same issues.Is there any workaround using pm2-rotatelogs itself without designing own solution

**Comment by anthonywebb** [comment]
Raspberry pi users like me would appreciate something like this

**Comment by vmarchaud** [comment]
Published under version `2.1.0`, tell me if its good for you :)

**Comment by kishoreknowapp** [comment]
> Published under version `2.1.0`, tell me if its good for you :)

Is there any documentation available on how to use this?
