### ISSUE TITLE
pm2 set pm2-logrotate:max_size 

### ISSUE THREAD

**Issue by bschelling** [pm2-hive/pm2-logrotate#37]
Just started using pm2-logrotate and immediately ran into an issue. I'm not sure whether this is expected behaviour but at least its a warning to anybody trying to do the same.

I had a 27GB logfile on a server that was running for a long time.
I ran `pm2 set pm2-logrotate:max_size 1G`

 What I expected was that on the default time (midnight) the huge logfile would be moved and from then on logrotate would check for files > 1GB at the time specified.

What actually happened was that a number of logfiles were generated in parallel immediately and I almost ran out of disk since the orginal logfile didn't get smaller. 

pm2 list showed pm2-logrotate as an activated module, but `pm2 stop pm2-logrotate` only resulted in "Process pm2-logrotate not found".

In the end i went on a killing spree and deleted the pm2 god as well as the node processes and deleted the huge log file.

**Comment by vmarchaud** [comment]
I'm interested, could you come over our slack [here](http://slack.pm2.io) and tell me more about what happened ? Thanks

**Comment by bschelling** [comment]
ok there

**Comment by vmarchaud** [comment]
Published a new version with few fixes, can you try it out ?

Regards
