### ISSUE TITLE
retain not work when customized error_file and out_file in pm2 app config

### ISSUE THREAD

**Issue by roytan883** [pm2-hive/pm2-logrotate#39]
pm2 can set app's log to different path by `error_file` and `out_file`. 

But pm2-logrotate only delete old log files in `PM2_ROOT_PATH + "/logs"`. 

If my app customized `error_file` and `out_file`, then **retain** not work. old logs keep increase.

**Comment by roytan883** [comment]
please review this PR:
https://github.com/pm2-hive/pm2-logrotate/pull/40

**Comment by weifansym** [comment]
Is the issue be solved？？

**Comment by roytan883** [comment]
yes, it will be solved if the author accept the PR. 

It works for me, when a changed app's `error_file` and `out_file` path.

**Comment by vmarchaud** [comment]
Sorry i forgot this issue, merged and will publish the new version soon.
Thanks for your contribution
