### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by panuhorsmalahti** [pm2-hive/pm2-logrotate#4]
I get the following error on Windows, which causes pm2-logrotate to restart

```
TypeError: Cannot read property 'length' of undefined
    at C:\Users\panu\.pm2\node_modules\pm2-logrotate\app.js:28:32
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by jshkurti** [comment]
@daraghking

**Comment by daraghking** [comment]
Sorry about that I don't use windows myself and I though there was nothing linux specific. I never thought of the windows path backslash difference.
Looking back it was a bit hacky and I should have used something like the path module @panuhorsmalahti used in his fix.
