### ISSUE TITLE
module doesn't start

### ISSUE THREAD

**Issue by CeDeZ** [pm2-hive/pm2-logrotate#44]
Hello, 
I copied the whole folder  (../.pm2/node_modules/pm2-logrotate) to the same directory on a machine without internet access but the module doesn't start, even after a reboot. 
How can I activate it or install it on an offline machine? 
thanks in advance

**Comment by vmarchaud** [comment]
`git clone https://github.com/pm2-hive/pm2-logrotate && cd pm2-logrotate && pm2 install .`

**Comment by CeDeZ** [comment]
I downloaded it from github, extracted the .zip file, switched to the folder and ran "pm2 install".
It says "error: missing required argument 'module;git:/'.
If I run "pm2 install pm2-logrotate" it says "installung module pm2-logrotate > module already installed. updating. > calling [npm] registry... and tries to download the files" but as I said, there's no internet access on that machine

**Comment by CeDeZ** [comment]
I managed to get pm2-logrotate module "working". It actually starts and runs for a few seconds before it errors. I get the following errors:

Error: Cannot find module 'pmx'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\username\.pm2\node_modules\pm2-logrotate\app.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I tried downloading pmx on my machine, export a .tgz file to the offline machine and install it but it didn't change anything. Any ideas?

**Comment by CeDeZ** [comment]
kinda solved it by copying the folder from my local machine.
after that I started the console and jumped in there > Ran "pm2 install ." to activate the module
and edited the module-config file in the pm2 home directory (enabled pm2-logrotate).
