### ISSUE TITLE
TypeError: "listener" argument must be a function

### ISSUE THREAD

**Issue by mike-aungsan** [pm2-hive/pm2-logrotate#48]
5|pm2-logr |     at Socket.once (events.js:307:11)
5|pm2-logr |     at Socket.connect (net.js:943:10)
5|pm2-logr |     at Socket.connect (/usr/lib/node_modules/pm2/node_modules/async-listener/index.js:76:27)5|pm2-logr |     at ReqSocket.Socket.connect (/home/ubuntu/.pm2/node_modules/pm2-axon/lib/sockets/sock.js
:295:8)
5|pm2-logr |     at Object.InteractorDaemonizer.ping (/home/ubuntu/.pm2/node_modules/pm2/lib/Interactor/I
nteractorDaemonizer.js:52:7)
5|pm2-logr |     at Object.InteractorDaemonizer.getInteractInfo (/home/ubuntu/.pm2/node_modules/pm2/lib/I
nteractor/InteractorDaemonizer.js:474:24)
5|pm2-logr |     at new module.exports (/home/ubuntu/.pm2/node_modules/pm2/lib/API.js:124:12)
5|pm2-logr |     at Object.<anonymous> (/home/ubuntu/.pm2/node_modules/pm2/index.js:11:18)
5|pm2-logr |     at Module._compile (module.js:571:32)
5|pm2-logr |     at Object.Module._extensions..js (module.js:580:10)
5|pm2-logr | TypeError: "listener" argument must be a function
5|pm2-logr |     at Socket.once (events.js:307:11)
5|pm2-logr |     at Socket.connect (net.js:943:10)
5|pm2-logr |     at Socket.connect (/usr/lib/node_modules/pm2/node_modules/async-listener/index.js:76:27)
5|pm2-logr |     at ReqSocket.Socket.connect (/home/ubuntu/.pm2/node_modules/pm2-axon/lib/sockets/sock.js
:295:8)
5|pm2-logr |     at Object.InteractorDaemonizer.ping (/home/ubuntu/.pm2/node_modules/pm2/lib/Interactor/I
nteractorDaemonizer.js:52:7)
5|pm2-logr |     at Object.InteractorDaemonizer.getInteractInfo (/home/ubuntu/.pm2/node_modules/pm2/lib/I
nteractor/InteractorDaemonizer.js:474:24)
5|pm2-logr |     at new module.exports (/home/ubuntu/.pm2/node_modules/pm2/lib/API.js:124:12)
5|pm2-logr |     at Object.<anonymous> (/home/ubuntu/.pm2/node_modules/pm2/index.js:11:18)
5|pm2-logr |     at Module._compile (module.js:571:32)
5|pm2-logr |     at Object.Module._extensions..js (module.js:580:10)

**Comment by vhain** [comment]
Are you using Node 7.7.2? It can be bug of it. https://github.com/nodejs/node/pull/11762

**Comment by mike-aungsan** [comment]
Yes I just found. Thanks
