### ISSUE TITLE
Feature request: UTC option

### ISSUE THREAD

**Issue by struanb** [pm2-hive/pm2-logrotate#50]
We require all our log filename dates to be in utc. It's easy to patch the call to moment().format(..) as moment().utc().format(...) but it would be useful to have an option for this.

**Comment by nitrocode** [comment]
Possible this can be closed pending approval of PR https://github.com/pm2-hive/pm2-logrotate/pull/77

**Comment by vmarchaud** [comment]
Published under 2.4.0
