### ISSUE TITLE
There is memory leak？

### ISSUE THREAD

**Issue by snadn** [pm2-hive/pm2-logrotate#53]
![image](https://cloud.githubusercontent.com/assets/1269858/25602997/c7011aa8-2f2a-11e7-9aa4-147b711a625e.png)

**Comment by Unitech** [comment]
Confirmed

**Comment by rjforbes** [comment]
![image](https://cloud.githubusercontent.com/assets/344442/26152238/7d20db0e-3adc-11e7-9258-cbe8c1092237.png)
Also seeing here steadily growing over time.

**Comment by isaachinman** [comment]
Also have a `pm2-logrotate` process consuming over 1GB of memory. Serious issue.

**Comment by Equim-chan** [comment]
Same here. And it increased the memory usage of `pm2` itself too.

**Comment by isaachinman** [comment]
Sorry to bump again, but how long will this sit open? Memory leaking up to 1GB makes it absolutely irresponsible to use this util in production, lest we start rotating our log rotation processes.

**Comment by checor** [comment]
My memory size is slowly increasing too currently sitting at 233 MB. I will keep an eye if it increases to big size like the other guys do.

**Comment by Kevalin** [comment]
Same here. Memory is so big.
Here is my pm2 conf
== module-db ==
┌───────────────┬───────┐
│ key           │ value │
├───────────────┼───────┤
│ pm2-logrotate │ true  │
└───────────────┴───────┘
== pm2-logrotate ==
┌────────────────┬───────────┐
│ key            │ value     │
├────────────────┼───────────┤
│ max_size       │ 200M      │
│ compress       │ false     │
│ workerInterval │ 30        │
│ rotateInterval │ 0 0 * * * │
└────────────────┴───────────┘
pm2  version 2.1.6
pm2-logrotate version 2.2.0
os centos

**Comment by ipengyo** [comment]
I also encountered this situation, currently hovering around 200M

**Comment by isaachinman** [comment]
@Unitech What do you need from us to confirm this issue?

**Comment by dcsan** [comment]
how else are people addressing this?
are there any other log-rotate options that play nice with pm2 ?

$ pm2 restart pm2-logrotate

**Comment by isaachinman** [comment]
@dcsan How else are people addressing this?

Use docker.

**Comment by dcsan** [comment]
but pm2 logs will still be piling up somewhere.

**Comment by Equim-chan** [comment]
@dcsan I use logrotated instead. Check https://github.com/Unitech/pm2/blob/master/lib/templates/logrotate.d/pm2

**Comment by sashakirichek** [comment]
https://www.npmjs.com/package/pm2-logrotate-imp

**Comment by ADumaine** [comment]
Any solution to this?
I just installed log-rotate last night and after 12 hours the app that usually takes less than 200MB is up to 1.5GB.

```
┌──────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬──────────┬──────────┬──────────┐
│ App name │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem      │ user     │ watching │
├──────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼──────────┼──────────┼──────────┤
│ snserver │ 0  │ fork │ 21706 │ online │ 118     │ 12h    │ 0%  │ 1.5 GB   │ srvadmin │ disabled │
└──────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴──────────┴──────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬──────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │ user     │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼──────────┤
│ pm2-logrotate │ 2.2.0   │ N/A        │ online │ 1       │ 0%  │ 30.215 MB   │ srvadmin │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴──────────┘
```

I tried updating pm2 from 2.6.1 to 2.7.1  and restarted.  
Still has an issue. App memory has tripled in 3 hours (200MB to 300MB).   This is unusable. I have to uninstall it.

**Comment by dcsan** [comment]
you could setup a cron task to `pm2 restart pm2-logrotate` every hour 👯‍♂️
