### ISSUE TITLE
Replace fs package with graceful-fs

### ISSUE THREAD

**Issue by MonkeyDo** [pm2-hive/pm2-logrotate#57]
I've had some issues on Windows, which I suspect have to do with the fs package.

I suggest replacing fs with graceful-fs which is a very minimal change for a high potential gain.

https://github.com/isaacs/node-graceful-fs

**Comment by vmarchaud** [comment]
Feel free to make a PR and we will merge it :)

**Comment by MonkeyDo** [comment]
Sure thing; just wanted to make sure you're not against it before putting in the whole 5 minutes of work needed :D

**Comment by vmarchaud** [comment]
Thanks for the PR, will publish it soon (ping me if not i might forget)
