### ISSUE TITLE
workerInterval - based on last rotate time or system time?

### ISSUE THREAD

**Issue by nitrocode** [pm2-hive/pm2-logrotate#65]
Here are my pm2 log rotate settings:

```
$ pm2 get pm2-logrotate
┌────────────────┬──────────────┐
│ key            │ value        │
├────────────────┼──────────────┤
│ max_size       │ 10           │
│ retain         │ all          │
│ compress       │ true         │
│ dateFormat     │ YYYYMMDDHHmm │
│ workerInterval │ 3700         │
│ rotateInterval │ 0 */1 * * *  │
│ rotateModule   │ true         │
└────────────────┴──────────────┘
```

I meant to set the max_size to `10G` but mistakenly set it to `10` with a workerInterval of 3700 seconds which should be unreachable. We're gzipping all rotated files, the data format should match the above but the "mm" should become zeroes because of the rotateInterval cron which should be rotating every hour on the 0th minute.

Here is an example of our log files from PM2

```
app-4__201709191030.log.gz
app-4__201709191100.log.gz
app-4__201709191131.log.gz
app-4__201709191200.log.gz
app-4__201709191233.log.gz
app-4__201709191300.log.gz
```

It should look more like

```
app-4__201709191100.log.gz
app-4__201709191200.log.gz
app-4__201709191300.log.gz
```

Even though the max_size is set so low, it shouldn't check the filesize until 3700 seconds from the last rotation. 

Does the workerInterval start its timer based on when pm2 started or it's log rotation (either by rotate or worker interval)?

**Comment by vmarchaud** [comment]
when the module is started in case you didn't figure it yet ;)

**Comment by nitrocode** [comment]
That's one interesting part about it. The worker interval 3700 seconds is outside the scope of the hour, the max size for the worker interval is unattainable, and the rotate cron is set to rotate the logs on the 0th minute of every hour so how can the log files between even be possible?

I haven't seen this for a while so perhaps something in our environment was causing this..

**Comment by vmarchaud** [comment]
Actually the worker is independent from the `rotateInterval`, the later force the rotation in contrary of the worker that respect the max file size configured :)
So its possible that file are getting rotated between every hour

**Comment by nitrocode** [comment]
Oh ok so both rotateInterval and workerInterval will respect the max file size configured. 

I found a workaround for this by setting my workerInterval much higher, my dateFormat to `YYYYMMDDHH00` instead of using the `mm` minutes, and set max_size to `100G`.

**Comment by vmarchaud** [comment]
Nope, the rotateInterval force the rotation regardless of the size
