### ISSUE TITLE
high cpu usage if log file exceed max_size

### ISSUE THREAD

**Issue by chenghung** [pm2-hive/pm2-logrotate#66]
config:
```
pm2 set pm2-logrotate:max_size 1G
```
![2017-09-28 16-48-14](https://user-images.githubusercontent.com/3082432/30958816-df5635a0-a470-11e7-88e7-dc3eee260af8.png)

**Comment by vmarchaud** [comment]
CPU Usage should be low, you just happen to look when there was activity (for example when gziping the logs)

**Comment by zyf0330** [comment]
If large amount logs are producing all the time, then cpu usage will keep high.

**Comment by zyf0330** [comment]
I just find the process is, original log file is read as ReadStream then write to new file, through gzip if compress is true. Its cpu usage is high. If log amount increases faster than this process, cpu usage keep high.
So why not:
1. just move original log file to new file.
2. then compress it if need.

**Comment by liesislukas** [comment]
it was eating CPU like crazy constantly zipping the files these was the solution:

pm2 set pm2-logrotate:compress false
pm2 set pm2-logrotate:max_size 500Mb
pm2 set pm2-logrotate:retain 1

while my logs are extracted to 3rd party anyways, i don't need retain
