### ISSUE TITLE
Installation failed - pm2 install pm2-logrotate

### ISSUE THREAD

**Issue by sunnyfrancis** [pm2-hive/pm2-logrotate#69]
Hi,
While trying to install pm2-logrotate module I'am getting below installation failed.

_[PM2][Module] Installing module pm2-logrotate
[PM2][Module] Calling [YARN] to install pm2-logrotate ...
Error: Could not find or load main class add
[PM2][ERROR] Installation failed_

I tried cleaning node, pm2 and npm cache but still getting the same error. 
Is there way I can get detailed error for this failure?

Thanks in advance.

**Comment by vmarchaud** [comment]
Cannot reproduce, can you share your versions of Node/NPM/PM2 please  ?

**Comment by adamreisnz** [comment]
Under the hood, pm2 just uses Yarn to do the install, but unless I'm mistaken, I think it should install it globally, and not try to find a local package. E.g. don't use `yarn add pm2-logrotate` but `npm i -g pm2-logrotate`.
