### ISSUE TITLE
Configuration for an offset or timezone to add / subtract time from rotated log names

### ISSUE THREAD

**Issue by nitrocode** [pm2-hive/pm2-logrotate#76]
Originally wrote this on the pm2 issues page https://github.com/Unitech/pm2/issues/3279 and it seems more relevant here since this module adds the timestamp based on system time using moment.js.

TLDR: I have date getting into my logs for hour 14 to hour 15 and the logs rotate on hour 15 with the name of hour 15. So the full name would be `app__201711131500.log.gz` and I'd like it to be offsetted by an hour so it will become `app__201711131500.log.gz`.

I played with the moment.js library and there doesn't seem to be a `format()` available to easily subtract an hour without modifying the `pm2-logrotate` code. Would you accept a PR for a new parameter? `timezone` or `offset` ?

**Comment by nitrocode** [comment]
Duplicate of https://github.com/pm2-hive/pm2-logrotate/issues/50

**Comment by vmarchaud** [comment]
Published under 2.4.0
