### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Climax777** [pm2-hive/pm2-logrotate#8]
Hello

I have a simple setup with only one active app, but pm2-logrotate uses 108MB.
![image](https://cloud.githubusercontent.com/assets/768925/9435647/c5fb80ca-4a49-11e5-9376-a4ba599bff44.png)

(also note the double % sign??)

**Comment by jhermsmeier** [comment]
Same here; 110+ MB with a single app running. While tailing the logs, I also noticed that it's creating its own logfile over and over every couple of seconds.

**Comment by alavit-d** [comment]
New version live on npm - 1.3.1 using streams, should use less memory. Reopen if problems persist :)

**Comment by SockRobber** [comment]
Using 1.3.1 I'm getting ~155MB usage. Only have one active app in pm2. Seems fairly high. Let me know if you need any additional details.

**Comment by Cyberuben** [comment]
I have the same issue here, using 128MB of RAM running only 2 simple applications
