### ISSUE TITLE
max_size on README

### ISSUE THREAD

**Issue by bicho** [pm2-hive/pm2-logrotate#9]
max_size... KB or MB?

e.g: pm2 set pm2-logrotate:max_size 1024 (1KB) pm2 set pm2-logrotate:interval_unit 'MM' (Months)

To:
e.g: pm2 set pm2-logrotate:max_size 1024 <b>(1MB)</b> pm2 set pm2-logrotate:interval_unit 'MM' (Months)

**Comment by jshkurti** [comment]
It's in bytes.

**Comment by bicho** [comment]
thx
